In [12]:
import numpy as np
import pandas as pd
import networkx as nx
import graphviz

ModuleNotFoundError: No module named 'graphviz'

In [4]:
a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [10]:
df = pd.DataFrame(a)

In [14]:
print ("hello")

hello

In [7]:
display(df)

   0
0  1
1  2
2  3

In [8]:
print("Hello")

Hello

# Bonjour

In [9]:
print('YEA')

YEA

In [22]:
import numpy
import numpy as np
import pandas as pd
import random

for k in range(1, 101):

    #set the range of the list (make it possible for repetitive num)
    num_list = [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 4]

    #initialize the matrix
    matrix = np.zeros((90, 12))
    colums = {"chrom1", "chrom2", "chrom3", "gene1", "gene2", "gene3", "gene4", "gene5", "gene6", "gene7", "gene8", "cellnum"}

    for i in range(90):
        for j in range(12):
            matrix[i][j] = random.choice(num_list)
            
    matrix_df = pd.DataFrame(matrix.astype(int), columns=colums)
    
    matrix_df.to_csv('patient' + str(k) + 'DCIS_.csv', sep='\t')

        
#     np.savetxt(, matrix.astype(int), fmt='%s')

In [23]:
display(matrix_df)

,gene4,gene5,cellnum,gene7,gene1,gene3,gene8,gene6,gene2,chrom3,chrom2,chrom1
0,2,2,1,1,2,3,3,2,1,1,1,4
1,2,2,2,1,2,2,1,2,4,3,2,1
2,2,2,1,1,1,1,2,2,2,1,2,2
3,2,1,2,2,4,1,2,1,2,3,2,1
4,1,2,2,3,1,2,2,2,2,2,2,4
5,1,1,1,4,1,2,2,4,2,1,2,2
6,1,2,2,1,1,1,1,2,2,3,4,2
7,2,2,2,1,2,2,2,2,2,2,2,2
8,1,2,3,2,2,3,1,2,2,2,1,2
9,2,1,3,2,2,2,1,3,1,2,3,2
10,2,2,1,3,2,2,2,3,3,2,1,1
11,3,2,2,2,2,2,3,1,2,2,3,1
12,3,2,2,1,2,2,2,4,2,1,1,4
13,2,2,2,1,2,2,2,1,2,1,3,2
14,2,2,2,3,1,1,1,2,2,2,2,3
15,1,1,2,1,1,2,2,1,1,1,1,2
16,2,2,3,2,2,1,1,3,3,4,2,1
17,1,2,2,2,2,2,2,2,2,2,2,2
18,2,2,2,3,1,2,1,1,2,2,2,3
19,3,1,1,1,1,3,2,2,1,4,2,2
20,1,1,4,2,2,1,1,2,1,2,2,2
21,2,2,2,1,1,1,4,1,1,1,1,1
22,2,2,1,1,3,2,2,1,2,2,1,2
23,1,3,2,4,1,1,2,2,1,2,2,2
24,2,2,4,2,2,2,2,2,2,1,2,2
25,2,2,1,3,2,1,2,1,2,2,2,2
26,1,2,3,2,1,2,4,2,2,2,2,1
27,2,2,1,2,2,1,1,2,2,2,2,1
28,2,1,1,2,2,2,2,2,2,2,2,1
29,3,1,4,2,4,2,4,2,2,1,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
60,2,2,1,2,2,2,1,2,2,2,2,1
61,2,2,2,2,2,2,2,2,2,3,1,3
62,1,2,1,3,2,2,2,2,2,4,4,2
63,2,2,2,2,1,1,3,2,1,2,1,2
64,2,2,1,2,2,3,1,2,1,2,1,2
65,1,2,2,1,2,2,1,2,2,2,2,2
66,2,2,3,1,2,2,2,1,2,2,2,2
67,2,2,2,2,2,2,1,2,1,4,2,3
68,3,1,2,2,3,2,1,2,2,2,2,1
69,2,2,2,2,2,2,1,2,1,2,2,3
70,3,2,1,2,2,2,4,3,2,2,2,2
71,2,2,4,2,2,1,3,2,2,2,1,1
72,1,3,4,2,4,3,2,1,3,1,2,4
73,2,2,4,2,2,2,2,2,1,3,3,2
74,2,1,2,3,2,1,2,2,2,2,2,1
75,3,2,1,1,1,2,2,1,4,1,2,2
76,1,1,2,3,4,2,2,2,1,3,3,1
77,2,3,2,3,2,1,4,2,4,2,1,2
78,2,2,2,2,2,2,2,1,2,4,2,3
79,2,2,2,2,2,2,2,4,3,2,1,2
80,1,2,1,2,1,2,1,2,2,1,4,1
81,2,2,2,1,1,1,2,2,2,3,2,2
82,2,3,4,2,2,2,2,2,2,1,2,1
83,1,1,2,1,2,2,3,1,2,2,1,4
84,1,2,2,2,2,1,4,1,2,3,1,3
85,4,1,2,2,1,2,1,1,2,2,2,2
86,1,2,2,2,1,1,1,2,2,1,2,1
87,2,3,2,1,4,1,2,2,2,2,3,1
88,2,2,2,2,1,2,2,2,1,1,3,2
89,3,2,3,4,1,1,4,2,2,2,1,1